# app/errors.py
class XtractorError(Exception): ...
class UserInputError(XtractorError): ...
class CancelledError(XtractorError): ...

class PdfOpenError(XtractorError): ...
class PdfReadError(XtractorError): ...
class ExcelWriteError(XtractorError): ...
class OCRError(XtractorError): ...

