from typing import Iterable, Protocol, List

class ExcelPort(Protocol):
    def open(self, output_path: str, headers: List[str]) -> None: ...
    def append_row(self, row: List[str]) -> None: ...
    def save_and_close(self) -> None: ...
