from typing import Iterable, Protocol, Tuple, List

Rect = Tuple[float, float, float, float]

class PdfPort(Protocol):
    def page_count(self, pdf_path: str) -> int: ...
    def get_page_size(self, pdf_path: str, page_index: int) -> Tuple[float, float]: ...
    def extract_text_in_rect(self, pdf_path: str, page_index: int, rect: Rect) -> str: ...
